kzi-nastava/ma-project-event-planner-siit-2024-team-23

app/src/main/java/com/example/fusmobilni/adapters/CategoryAdapter.java, app/src/main/java/com/example/fusmobilni/adapters/CategoryProposalAdapter.java, app/src/main/java/com/example/fusmobilni/fragments/CategoryProposalsPage.java, app/src/main/java/com/example/fusmobilni/fragments/DeleteCategoryFragment.java, app/src/main/java/com/example/fusmobilni/fragments/OfferingsPage.java, app/src/main/java/com/example/fusmobilni/interfaces/CategoryProposalListener.java, app/src/main/java/com/example/fusmobilni/model/CategoryProposal.java, app/src/main/java/com/example/fusmobilni/viewModels/CategoryProposalViewModel.java, app/src/main/res/layout/category_proposal_card.xml, app/src/main/res/layout/fragment_category_proposals_page.xml, app/src/main/res/layout/fragment_delete_category.xml, app/src/main/res/navigation/unauth_user_nav.xml, app/src/main/res/values/strings.xml
Implemented Category proposal page for admin so he can modify or approve category creation requests
You can navigate to this page from categories page.
=> [merge] category proposals page

app/src/main/java/com/example/fusmobilni/adapters/CategoryProposalAdapter.java, app/src/main/java/com/example/fusmobilni/fragments/CategoryProposalsPage.java, app/src/main/java/com/example/fusmobilni/fragments/ModifyCategoryProposalFragment.java, app/src/main/java/com/example/fusmobilni/interfaces/CategoryProposalListener.java, app/src/main/java/com/example/fusmobilni/model/CategoryProposal.java, app/src/main/java/com/example/fusmobilni/viewModels/CategoryProposalViewModel.java, app/src/main/res/layout/category_proposal_card.xml, app/src/main/res/layout/fragment_modify_category_proposal.xml, app/src/main/res/navigation/unauth_user_nav.xml, app/src/main/res/values/strings.xml
Admin can now approve category proposal as is
He can also edit the category proposal or just the existing one for the service/product the category was meant for
When editing the category proposal, admin can see the name and description of service/product he is editing proposal for
=> [merge] category proposal modal into develop

app/src/main/java/com/example/fusmobilni/fragments/MultiStepServiceFormOne.java, app/src/main/java/com/example/fusmobilni/viewModels/ServiceViewModel.java, app/src/main/res/layout/fragment_multi_step_service_form_one.xml, app/src/main/res/values/strings.xml
Service provider can now choose to create custom category for his event
He can then enter category name and description
Also he cannot update the category of a service no more
=> [merge] service form fix

app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsResponseAdapter.java, app/src/main/java/com/example/fusmobilni/clients/services/products/ProductsService.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/filters/ProductFilterFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/filters/ProductSearchFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/Filters/ServiceSearchFragment.java, app/src/main/java/com/example/fusmobilni/responses/items/products/filter/ProductPaginationResponse.java, app/src/main/java/com/example/fusmobilni/responses/items/products/filter/ProductsMinMaxPriceResponse.java, app/src/main/java/com/example/fusmobilni/viewModels/events/filters/EventSearchViewModel.java, app/src/main/java/com/example/fusmobilni/viewModels/items/product/filters/ProductSearchViewModel.java, app/src/main/java/com/example/fusmobilni/viewModels/items/service/filters/ServiceSearchViewModel.java, app/src/main/res/layout/fragment_product_search.xml, app/src/main/res/layout/product_card_horizontal.xml
Refactored and implmented synce with back end for product searching, filtering and pagination thru retrofit requests.
=> [merge]  search, pagination and filtering working with back end

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/fusmobilni/activities/FastRegisterActivity.java, app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java, app/src/main/java/com/example/fusmobilni/clients/services/events/inivtations/InvitationsService.java, app/src/main/java/com/example/fusmobilni/clients/services/fastRegister/FastRegisterService.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/InvitationsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/register/fast/HashInvalidFragment.java, app/src/main/java/com/example/fusmobilni/requests/events/invitations/InvitationCreateRequest.java, app/src/main/java/com/example/fusmobilni/requests/events/invitations/InvitationsCreateRequest.java, app/src/main/java/com/example/fusmobilni/requests/register/fast/FastRegisterRequest.java, app/src/main/java/com/example/fusmobilni/responses/FastRegisterInvitationResponse.java, app/src/main/java/com/example/fusmobilni/responses/events/invitations/InvitationResponse.java, app/src/main/java/com/example/fusmobilni/responses/events/invitations/InvitationsResponse.java, app/src/main/java/com/example/fusmobilni/viewModels/events/event/InvitationsViewModel.java, app/src/main/res/layout/fragment_hash_invalid.xml, app/src/main/res/layout/fragment_invitations.xml, app/src/main/res/layout/fragment_step_two_fast_registration.xml
Implemented retrofit service so user can recieve an invitation on email thru mobile.
=> [merge] event invitations sync with back end

app/build.gradle, app/src/main/java/com/example/fusmobilni/adapters/events/event/EventsHorizontalAdapter.java, app/src/main/java/com/example/fusmobilni/adapters/loading/LoadingCardHorizontalAdapter.java, app/src/main/java/com/example/fusmobilni/adapters/loading/LoadingCardVerticalAdapter.java, app/src/main/java/com/example/fusmobilni/fragments/HomeFragment.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/filters/EventFilterFragment.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/filters/EventSearchFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/filters/ProductFilterFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/filters/ProductSearchFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/Filters/ServiceFragmentFilter.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/Filters/ServiceSearchFragment.java, app/src/main/java/com/example/fusmobilni/fragments/loading/LoadingCardHorizontalFragment.java, app/src/main/java/com/example/fusmobilni/fragments/loading/LoadingCardVerticalFragment.java, app/src/main/java/com/example/fusmobilni/viewModels/events/filters/EventSearchViewModel.java, app/src/main/java/com/example/fusmobilni/viewModels/items/product/filters/ProductSearchViewModel.java, app/src/main/java/com/example/fusmobilni/viewModels/items/service/filters/ServiceSearchViewModel.java, app/src/main/res/layout/event_card_horizontal.xml, app/src/main/res/layout/event_fragment_search.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_loading_card_horizontal.xml, app/src/main/res/layout/fragment_loading_card_vertical.xml, app/src/main/res/layout/fragment_product_search.xml, app/src/main/res/layout/fragment_service_search.xml, app/src/main/res/layout/product_card_horizontal.xml, app/src/main/res/layout/service_card_horizontal.xml, app/src/main/res/values/colors.xml
Added loading cards for event, service and product cards on home page as well as respectful fragments for searching and filtering.
=> [merge] redesigned cards and loading cards into develop

app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/CreateEventStepTwo.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/InvitationsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceReservationFragment.java
Fixed validation on service reservation page so the Event Organizer cannot reserve a service with starting time being greater than ending time.
=> [merge] fixed validation on service reservation page

app/src/main/java/com/example/fusmobilni/adapters/AdapterUtils.java, app/src/main/java/com/example/fusmobilni/adapters/events/event/EventsAdapter.java, app/src/main/java/com/example/fusmobilni/adapters/events/event/EventsHorizontalAdapter.java, app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsAdapter.java, app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsResponseAdapter.java, app/src/main/java/com/example/fusmobilni/adapters/items/service/ServiceHorizontalAdapter.java, app/src/main/java/com/example/fusmobilni/adapters/items/service/ServicesAdapter.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsRegularFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceReservationFragment.java, app/src/main/java/com/example/fusmobilni/responses/events/filter/EventPaginationResponse.java, app/src/main/java/com/example/fusmobilni/responses/events/home/EventHomeResponse.java, app/src/main/java/com/example/fusmobilni/responses/items/products/filter/ProductPaginationResponse.java, app/src/main/java/com/example/fusmobilni/responses/items/products/home/ProductHomeResponse.java, app/src/main/java/com/example/fusmobilni/responses/items/services/ServiceOverviewResponse.java, app/src/main/java/com/example/fusmobilni/responses/items/services/ServiceReservationResponse.java, app/src/main/java/com/example/fusmobilni/responses/items/services/filter/ServicePaginationResponse.java, app/src/main/java/com/example/fusmobilni/responses/items/services/home/ServiceHomeResponse.java, app/src/main/res/layout/event_card_horizontal.xml, app/src/main/res/layout/fragment_loading_card_horizontal.xml, app/src/main/res/layout/fragment_service_details_regular.xml, app/src/main/res/layout/product_card_horizontal.xml, app/src/main/res/navigation/unauth_user_nav.xml
Implemented loading images from back end for products, services and events
=> [feature] loading images for events,services,products

app/src/main/java/com/example/fusmobilni/activities/RegisterActivity.java, app/src/main/java/com/example/fusmobilni/clients/auth/AuthService.java, app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/StepOneFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/StepThreeFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/StepTwoFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/VerifyEmailFragment.java, app/src/main/java/com/example/fusmobilni/interfaces/ILocationCallback.java, app/src/main/java/com/example/fusmobilni/interfaces/IRegisterCallback.java, app/src/main/java/com/example/fusmobilni/requests/register/regular/RegisterRequest.java, app/src/main/java/com/example/fusmobilni/responses/register/regular/RegisterResponse.java, app/src/main/java/com/example/fusmobilni/viewModels/users/register/RegisterViewModel.java, app/src/main/res/layout/fragment_step_two.xml, app/src/main/res/values/strings.xml
User register with email verification connected to the be!
=> [merge] user register #1.1.5

app/src/main/java/com/example/fusmobilni/activities/HomeActivity.java, app/src/main/java/com/example/fusmobilni/activities/LoginActivity.java, app/src/main/java/com/example/fusmobilni/activities/RegisterActivity.java, app/src/main/java/com/example/fusmobilni/clients/AuthInterceptor.java, app/src/main/java/com/example/fusmobilni/clients/auth/AuthService.java, app/src/main/java/com/example/fusmobilni/core/CustomSharedPrefs.java, app/src/main/java/com/example/fusmobilni/fragments/users/profile/AboutUserFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/profile/UpdateProfileFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/profile/ViewProfileFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/StepOneFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/StepThreeFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/StepTwoFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/register/regular/VerifyEmailFragment.java, app/src/main/java/com/example/fusmobilni/interfaces/ILocationCallback.java, app/src/main/java/com/example/fusmobilni/interfaces/ILoginCallback.java, app/src/main/java/com/example/fusmobilni/interfaces/IRegisterCallback.java, app/src/main/java/com/example/fusmobilni/requests/auth/LoginRequest.java, app/src/main/java/com/example/fusmobilni/requests/register/regular/RegisterRequest.java, app/src/main/java/com/example/fusmobilni/responses/auth/LoginResponse.java, app/src/main/java/com/example/fusmobilni/responses/auth/UserAvatarResponse.java, app/src/main/java/com/example/fusmobilni/responses/register/regular/RegisterResponse.java, app/src/main/java/com/example/fusmobilni/viewModels/users/login/LoginViewModel.java, app/src/main/java/com/example/fusmobilni/viewModels/users/register/RegisterViewModel.java, app/src/main/res/layout/fragment_step_two.xml, app/src/main/res/layout/fragment_view_profile.xml, app/src/main/res/values/strings.xml
User login functionality connected with the BE and get profile image on the profile page integration!
=> [merge] User login #1.2.5

app/src/main/java/com/example/fusmobilni/adapters/items/pricelist/PriceListAdapter.java, app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java, app/src/main/java/com/example/fusmobilni/clients/services/items/pricelist/PriceListService.java, app/src/main/java/com/example/fusmobilni/fragments/items/pricelist/EditPriceListItemFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/pricelist/PriceListFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/Forms/MultiStepServiceFormOne.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsRegularFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceView.java, app/src/main/java/com/example/fusmobilni/interfaces/PriceListListener.java, app/src/main/java/com/example/fusmobilni/requests/items/pricelist/PriceListUpdateRequest.java, app/src/main/java/com/example/fusmobilni/responses/items/pricelist/PriceListGetResponse.java, app/src/main/java/com/example/fusmobilni/responses/items/pricelist/PriceListsGetResponse.java, app/src/main/java/com/example/fusmobilni/viewModels/items/pricelist/PriceListViewModel.java, app/src/main/java/com/example/fusmobilni/viewModels/items/service/ServiceViewModel.java, app/src/main/res/layout/fragment_edit_price_list_item.xml, app/src/main/res/layout/fragment_price_list.xml, app/src/main/res/layout/price_list_item.xml, app/src/main/res/menu/nav_menu_service_provider.xml, app/src/main/res/navigation/unauth_user_nav.xml, app/src/main/res/values/strings.xml
Service provider can now see his pricelist and can edit items
=> [merge] pricelist overview

app/src/main/java/com/example/fusmobilni/adapters/items/reviews/ItemReviewApprovalAdapter.java, app/src/main/java/com/example/fusmobilni/clients/services/items/ItemsService.java, app/src/main/java/com/example/fusmobilni/fragments/admin/ItemReviewApprovalFragment.java, app/src/main/java/com/example/fusmobilni/fragments/dialogs/FailiureDialogFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/reviews/ItemReviewApproveFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/reviews/OnReviewActionListener.java, app/src/main/java/com/example/fusmobilni/requests/items/AcceptanceState.java, app/src/main/java/com/example/fusmobilni/requests/items/ItemReviewUpdateStateRequest.java, app/src/main/java/com/example/fusmobilni/responses/items/ItemReviewResponse.java, app/src/main/java/com/example/fusmobilni/responses/items/ItemReviewsResponse.java, app/src/main/java/com/example/fusmobilni/responses/items/services/ServiceOverviewResponse.java, app/src/main/res/layout/fragment_item_review_approval.xml, app/src/main/res/layout/fragment_item_review_approve.xml, app/src/main/res/menu/nav_menu_unauth_user.xml, app/src/main/res/navigation/unauth_user_nav.xml
Upon accessing a item grade approval fragment, admin can now approve or decline pending item reviews. Approved reviews will later be shown on service and product details pages.
=> [merge] item grade approval for admin

app/src/main/java/com/example/fusmobilni/activities/HomeActivity.java, app/src/main/java/com/example/fusmobilni/clients/webSockets/ChatWebSocketClient.java, app/src/main/java/com/example/fusmobilni/clients/webSockets/NotificationWebSocketClient.java, app/src/main/java/com/example/fusmobilni/fragments/communication/NotificationsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/communication/chat/ChatFragment.java, app/src/main/java/com/example/fusmobilni/viewModels/notifications/NotificationViewModel.java
Redesigned notification logic to work with websockets. Now upon SP's review being acepted, he recieves a notification in real time that he can view on notificaitons fragment. SP gets notified thru the number of the badge in toolbar being updated.
=> [merge] redesigned notification logic into develop

app/build.gradle, app/src/main/java/com/example/fusmobilni/adapters/users/eventOrganizer/EventOrganizerEventAdapter.java, app/src/main/java/com/example/fusmobilni/clients/services/items/pricelist/PriceListService.java, app/src/main/java/com/example/fusmobilni/fragments/communication/chat/ChatFragment.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/EventDetailsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/CreateEventStepThree.java, app/src/main/java/com/example/fusmobilni/fragments/items/company/CompanyOverviewFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/pricelist/PriceListFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/ProductDetailsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsRegularFragment.java, app/src/main/java/com/example/fusmobilni/responses/users/GetCompanyOverviewResponse.java, app/src/main/res/layout/fragment_company_overview.xml, app/src/main/res/layout/fragment_e_o_event_card_horizontal.xml, app/src/main/res/layout/fragment_event_details.xml, app/src/main/res/layout/fragment_price_list.xml, app/src/main/res/navigation/unauth_user_nav.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/network_security_config.xml, gradle/libs.versions.toml
Service provider can now export his pricelist into pdf
He can also see his company overview
=> [merge] pricelist export into pdf

app/src/main/java/com/example/fusmobilni/adapters/users/serviceProvider/ServiceProviderProductAdapter.java, app/src/main/java/com/example/fusmobilni/clients/services/products/ProductsService.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/Forms/MultiStepProductFormOne.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/Forms/MultiStepProductFormThree.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/Forms/MultiStepProductFormTwo.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/ProductsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/filters/ProductFilterFragment.java, app/src/main/java/com/example/fusmobilni/requests/products/CreateProductProposalRequest.java, app/src/main/java/com/example/fusmobilni/requests/products/CreateProductRequest.java, app/src/main/java/com/example/fusmobilni/requests/products/GetProductResponse.java, app/src/main/java/com/example/fusmobilni/requests/products/GetProductsResponse.java, app/src/main/java/com/example/fusmobilni/requests/products/UpdateProductRequest.java, app/src/main/java/com/example/fusmobilni/viewModels/items/product/ProductViewModel.java, app/src/main/java/com/example/fusmobilni/viewModels/items/product/filters/ProductSearchViewModel.java, app/src/main/java/com/example/fusmobilni/viewModels/users/serviceProvider/ServiceProviderViewModel.java, app/src/main/res/layout/fragment_delete_service_modal.xml, app/src/main/res/layout/fragment_products.xml, app/src/main/res/layout/product_card_horizontal_sp.xml, app/src/main/res/navigation/unauth_user_nav.xml, app/src/main/res/values/strings.xml
Connected mobile product creation/update/delete/search with the BE
=> [merge] Product #3.22.2

app/src/main/java/com/example/fusmobilni/adapters/shared/ReviewFormAdapter.java, app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java, app/src/main/java/com/example/fusmobilni/clients/services/events/attendance/AttendanceService.java, app/src/main/java/com/example/fusmobilni/clients/services/events/reviews/EventReviewService.java, app/src/main/java/com/example/fusmobilni/fragments/communication/notifications/NotificationsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/EventDetailsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/reviews/EventReviewFormFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsRegularFragment.java, app/src/main/java/com/example/fusmobilni/requests/events/review/EventReviewCreateRequest.java, app/src/main/java/com/example/fusmobilni/responses/events/attendance/HasAttendedResponse.java, app/src/main/res/layout/fragment_event_review_form.xml, app/src/main/res/layout/fragment_notifications.xml, app/src/main/res/navigation/unauth_user_nav.xml
Implemented event grading for users who have attended the event and are not the organizer of the event in question.
=> [merge] event grading into develop

app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsAdapter.java, app/src/main/java/com/example/fusmobilni/clients/services/products/ProductsService.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/ProductsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceDetailsRegularFragment.java, app/src/main/java/com/example/fusmobilni/interfaces/item/BaseItem.java, app/src/main/java/com/example/fusmobilni/interfaces/item/ServiceOffering.java, app/src/main/java/com/example/fusmobilni/responses/items/products/ProductOverviewResponse.java
Added product details fragment reusing service details fragment. Should make it more generic in future!
=> [merge] Product/service details fragment with add to favorites functionality

app/src/main/java/com/example/fusmobilni/adapters/communication/notifications/NotificationsAdapter.java, app/src/main/java/com/example/fusmobilni/fragments/communication/notifications/NotificationsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/notifications/EventUpdateNotificationFragment.java, app/src/main/java/com/example/fusmobilni/fragments/notifications/EventUpdateNotificationUnreadFragment.java, app/src/main/res/layout/fragment_event_update_notification.xml, app/src/main/res/layout/fragment_event_update_notification_unread.xml
Implemented recieving event changes notifications regarding changes in products/services on the event and change of agenda, that user will recieve once Event Organizer updates anything on the event.
=> [merge] event changes notifications

app/src/main/java/com/example/fusmobilni/activities/LoginActivity.java, app/src/main/java/com/example/fusmobilni/adapters/admin/ReportApprovalAdapter.java, app/src/main/java/com/example/fusmobilni/adapters/communication/notifications/NotificationsAdapter.java, app/src/main/java/com/example/fusmobilni/clients/services/auth/AuthService.java, app/src/main/java/com/example/fusmobilni/clients/services/communication/reports/ReportsService.java, app/src/main/java/com/example/fusmobilni/fragments/admin/ReportApprovalFragment.java, app/src/main/java/com/example/fusmobilni/fragments/communication/reports/ReportApproveFragment.java, app/src/main/java/com/example/fusmobilni/interfaces/ILoginCallback.java, app/src/main/java/com/example/fusmobilni/interfaces/OnReportApprovalListener.java, app/src/main/java/com/example/fusmobilni/requests/communication/reports/ReportVerdict.java, app/src/main/java/com/example/fusmobilni/requests/communication/reports/UpdateReportStateRequest.java, app/src/main/java/com/example/fusmobilni/responses/auth/SuspensionResponse.java, app/src/main/java/com/example/fusmobilni/responses/communication/reports/ReportAdminResponse.java, app/src/main/java/com/example/fusmobilni/responses/communication/reports/ReportUserResponse.java, app/src/main/java/com/example/fusmobilni/responses/communication/reports/ReportsAdminResponse.java, app/src/main/java/com/example/fusmobilni/viewModels/users/login/LoginViewModel.java, app/src/main/res/layout/fragment_report_approval.xml, app/src/main/res/layout/fragment_report_approve.xml, app/src/main/res/menu/nav_menu_admin.xml, app/src/main/res/navigation/unauth_user_nav.xml
Implemented admin pages to suspend users, implemented displaying time untill suspension expiry.
=> [merge] admin pages for user reporting

app/src/main/java/com/example/fusmobilni/clients/ClientUtils.java, app/src/main/java/com/example/fusmobilni/clients/services/communication/blocks/BlockService.java, app/src/main/java/com/example/fusmobilni/clients/services/users/UserService.java, app/src/main/java/com/example/fusmobilni/fragments/communication/blocks/BlockModalFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/profile/foreign/ForeignUserProfileFragment.java, app/src/main/java/com/example/fusmobilni/interfaces/BlockDialogResultListener.java, app/src/main/java/com/example/fusmobilni/requests/communication/blocks/BlockCreateRequest.java, app/src/main/java/com/example/fusmobilni/responses/users/UserProfileResponse.java, app/src/main/res/layout/fragment_block_modal.xml, app/src/main/res/menu/ublock_report_menu.xml
User can now block/unblock a user on whose profile fragment he is located at the given moment.
=> [merge] user blocking on user profile fragment

app/build.gradle, app/src/main/java/com/example/fusmobilni/clients/services/events/EventsService.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/EventDetailsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/stats/EventStatisticsFragment.java, app/src/main/java/com/example/fusmobilni/responses/events/statistics/EventStatisticsResponse.java, app/src/main/java/com/example/fusmobilni/responses/events/statistics/GradeStatisticsResponseDTO.java, app/src/main/res/layout/fragment_event_component.xml, app/src/main/res/layout/fragment_event_details.xml, app/src/main/res/layout/fragment_event_statistics.xml, app/src/main/res/navigation/unauth_user_nav.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, gradle/libs.versions.toml
Event statistics connected with the BE. Added bar chart for displaying reviews!
=> [merge] Event stats connected with BE

app/src/main/java/com/example/fusmobilni/clients/services/events/EventsService.java, app/src/main/java/com/example/fusmobilni/fragments/HomeFragment.java, app/src/main/java/com/example/fusmobilni/viewModels/events/filters/EventSearchViewModel.java
Implemented blocking logic when user blocks the eo and otherwise, user will not be able to see events of that event organizer.
=> Feature/eo blocking #4.11.3

app/src/main/java/com/example/fusmobilni/clients/services/products/ProductsService.java, app/src/main/java/com/example/fusmobilni/clients/services/serviceOfferings/ServiceOfferingService.java, app/src/main/java/com/example/fusmobilni/fragments/HomeFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/Filters/ServiceSearchFragment.java, app/src/main/java/com/example/fusmobilni/viewModels/items/product/filters/ProductSearchViewModel.java, app/src/main/java/com/example/fusmobilni/viewModels/items/service/filters/ServiceSearchViewModel.java
Impelemted api call logic when sp is blocking a user or vice versa, user will not be able to view sp's items.
=> [merge] Sp blocking into develop

app/src/main/java/com/example/fusmobilni/adapters/items/service/ServiceReservationOverviewAdapter.java, app/src/main/java/com/example/fusmobilni/clients/services/serviceOfferings/ServiceOfferingService.java, app/src/main/java/com/example/fusmobilni/fragments/items/serviceReservationOverview/ServiceReservationsOverview.java, app/src/main/java/com/example/fusmobilni/model/enums/ReservationStatus.java, app/src/main/java/com/example/fusmobilni/responses/items/services/ServiceOfferingReservationForEventResponse.java, app/src/main/java/com/example/fusmobilni/responses/items/services/ServiceOfferingReservationsResponse.java, app/src/main/res/layout/fragment_service_reservations.xml, app/src/main/res/layout/service_reservation_overview_card.xml, app/src/main/res/menu/nav_menu_service_provider.xml, app/src/main/res/navigation/unauth_user_nav.xml, app/src/main/res/values/strings.xml
Service reservations accept/decline
=> [merge] event service reservations for sp

app/src/main/java/com/example/fusmobilni/fragments/items/service/Forms/MultiStepServiceFormTwo.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/ServiceView.java, app/src/main/java/com/example/fusmobilni/model/enums/DurationType.java, app/src/main/java/com/example/fusmobilni/model/items/service/PrototypeService.java, app/src/main/java/com/example/fusmobilni/requests/services/CreateProposalRequest.java, app/src/main/java/com/example/fusmobilni/requests/services/CreateServiceRequest.java, app/src/main/java/com/example/fusmobilni/requests/services/GetServiceResponse.java, app/src/main/java/com/example/fusmobilni/requests/services/UpdateServiceRequest.java, app/src/main/java/com/example/fusmobilni/viewModels/items/service/ServiceViewModel.java, app/src/main/res/layout/fragment_multi_step_service_form_two.xml, app/src/main/res/values/strings.xml
Service provider can now generate service with variable duration
=> [merge] service variable duration

app/build.gradle, app/src/main/java/com/example/fusmobilni/fragments/events/event/CreateEventFragment.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/EventDetailsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/CreateEventStepOne.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/createEventSteps/CreateEventStepTwo.java, app/src/main/java/com/example/fusmobilni/interfaces/CreateEventListener.java, app/src/main/java/com/example/fusmobilni/requests/events/event/CreateEventRequest.java, app/src/main/java/com/example/fusmobilni/responses/events/GetEventByIdResponse.java, app/src/main/java/com/example/fusmobilni/viewModels/events/event/EventViewModel.java, app/src/main/res/layout/fragment_create_event.xml, app/src/main/res/layout/fragment_create_event_step_one.xml, app/src/main/res/layout/fragment_event_details.xml, app/src/main/res/values/strings.xml, gradle/libs.versions.toml
=> [merge] event creation and event details map integration

app/src/main/java/com/example/fusmobilni/adapters/communication/chats/ChatAdapter.java, app/src/main/java/com/example/fusmobilni/fragments/events/event/CreateEventFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/category/CategoryCreationForm.java, app/src/main/java/com/example/fusmobilni/fragments/items/category/proposals/CategoryProposalsPage.java, app/src/main/java/com/example/fusmobilni/fragments/items/category/proposals/ModifyCategoryProposalFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/company/CompanyOverviewFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/ProductDetailsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/Forms/MultiStepServiceFormOne.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/Forms/MultiStepServiceFormThree.java, app/src/main/res/layout/chat_message.xml
Fixed back stack propagation errors
=> [merge] back stack issues

app/src/main/java/com/example/fusmobilni/adapters/users/UpgradeAccountAdapter.java, app/src/main/java/com/example/fusmobilni/clients/services/users/UserService.java, app/src/main/java/com/example/fusmobilni/core/CustomSharedPrefs.java, app/src/main/java/com/example/fusmobilni/fragments/users/userUpgrade/UpgradeUserConfirmUpgradeFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/userUpgrade/UpgradeUserFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/userUpgrade/UpgradeUserRoleSelectionFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/userUpgrade/UpgradeUserServiceProviderFragment.java, app/src/main/java/com/example/fusmobilni/requests/users/UpgradeUserRequest.java, app/src/main/java/com/example/fusmobilni/responses/users/UpgradedUserRoleResponse.java, app/src/main/java/com/example/fusmobilni/viewModels/notifications/NotificationViewModel.java, app/src/main/java/com/example/fusmobilni/viewModels/users/IUpgradeUserCallBack.java, app/src/main/java/com/example/fusmobilni/viewModels/users/UpgradeUserViewModel.java, app/src/main/res/layout/fragment_upgrade_user.xml, app/src/main/res/layout/fragment_upgrade_user_confirm_upgrade.xml, app/src/main/res/layout/fragment_upgrade_user_role_selection.xml, app/src/main/res/layout/fragment_upgrade_user_service_provider.xml, app/src/main/res/menu/nav_menu_auth_user.xml, app/src/main/res/navigation/unauth_user_nav.xml
Users who have logged on thru fast register can now upgrade to either Service Provider or Event Organizer
=> [merge] user upgrading into develop

app/src/main/java/com/example/fusmobilni/activities/VerifyEmailActivity.java, app/src/main/java/com/example/fusmobilni/adapters/items/product/ProductsResponseAdapter.java, app/src/main/java/com/example/fusmobilni/fragments/items/product/filters/ProductFilterFragment.java, app/src/main/java/com/example/fusmobilni/fragments/items/service/Filters/ServiceSearchFragment.java, app/src/main/java/com/example/fusmobilni/viewModels/users/login/LoginViewModel.java, app/src/main/res/layout/fragment_product_filter.xml, app/src/main/res/layout/fragment_service_provider_filter.xml
There was a mixup when loading a product search filter. When pressing filter button on "All products page" it would open up a service provider product filter instead, there for filtering not working as intended.
=> [fix] product search filter

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/fusmobilni/activities/HomeActivity.java, app/src/main/java/com/example/fusmobilni/helper/NotificationHelper.java, app/src/main/java/com/example/fusmobilni/viewModels/notifications/NotificationViewModel.java
Fixed the notifications so now they pop up when received!
=> [fix] notifications not popping

app/src/main/java/com/example/fusmobilni/fragments/items/product/ProductsFragment.java, app/src/main/java/com/example/fusmobilni/fragments/users/filters/ServiceProviderProductFilterFragment.java
Added deleted product filter fragment
=> [fix] add new product filter fragment
